version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000" # Adjust the port as necessary
    environment:
      DATABASE_URL: ${DATABASE_URL} # Using value from .env
    # depends_on:
    #   db:
    #     condition: service_healthy
#   db:
#     image: postgres:latest
#     restart: always
#     env_file:
#       - .env
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data
#     healthcheck:
#       test:
#         [
#           "CMD",
#           "pg_isready",
#           "-U",
#           "ramit",
#           "-d",
#           "recPlatform",
#           "-h",
#           "localhost",
#         ]
#       interval: 5s
#       timeout: 5s
#       retries: 5

# volumes:
#   db_data:
